### ISSUE TITLE
Sent 1 LTC to Blockcard - It disappeared from by blockcard balance

### ISSUE THREAD

**Issue by jeff169** [litecoin-foundation/litewallet-ios#15]
**Describe the bug**
5 days ago, I sent 1 LTC to my blockcard.  It appeared in the balance shortly afterwards, but then disappeared.

**To Reproduce**
Send 1 LTC from Litewallet to Blockcard using QR code

**Expected behavior**
Transactions should not diappear

**Screenshots**
![IMG_1216](https://user-images.githubusercontent.com/77628627/105647386-4d88e800-5e73-11eb-8620-3a97e4e6e1e4.PNG)
![blockcard](https://user-images.githubusercontent.com/77628627/105647552-82e20580-5e74-11eb-92b1-8490e79b9f08.JPG)

**Desktop (please complete the following information):**
IOS 14.3
Windows 10

**Smartphone (please complete the following information):**
Iphone 11
PC
 
**Additional context**

**Comment by kcw-grunt** [comment]
close due to inaction
