### ISSUE TITLE
🦺[Tech Debt] Remove cruft: BitID

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-ios#57]
## Goal 
**Describe the work to be done**
Remove any references to the original fork (Breadwallet) where `BitID` was used.  This was a service to be used by the BRD team and was never implemented in Litewallet (or Loafwallet). 

It causes confusion and problems maintaining the codebase.  **It must be removed safely**

## Definition of Done
- [x] Open a working branch and let @kcw-grunt know
- [x] Identify S,M,L refactors
- [x] Branch off the working branch and write issues for the refactors.
- [ ] Test with older and newer iOS devices and simulators

**Comment by kcw-grunt** [comment]
@JasperHeist I added #58 as a dependency to make sure  it was done first.

**Comment by JCHeist** [comment]
> @JasperHeist I added #58 as a dependency to make sure it was done first.

Do you want this or #58 done first? Right now it's showing this one has to be done first, is that what you wanted? @kcw-grunt

**Comment by JCHeist** [comment]
opened branch `techdebt/Remove-cruft-BitID-57`.  Can you confirm I interpreted the "blocking" thing right? or do you want the BCash stuff done first?

**Comment by kcw-grunt** [comment]
> > @JasperHeist I added #58 as a dependency to make sure it was done first.
> 
> Do you want this or #58 done first? Right now it's showing this one has to be done first, is that what you wanted? @kcw-grunt

Yes @JasperHeist you have interpreted this correctly The reason is BitID has less code and was never implemented by BRD/Breadwallet (from my quick assessment)
