### ISSUE TITLE
🦺[Tech Debt]  Remove Cruft: Bcash

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-ios#58]
**Describe the work to be done**
Remove any references to the original fork (Breadwallet) where `Bcash` was used.  This was because Breadwallet was a BTC wallet and the BRD team were going to allow use of Bcash.

For us it causes confusion and problems maintaining the codebase.  **It must be removed safely**

## Definition of Done
- [x] Open a working branch and let @kcw-grunt know
- [x] Identify S,M,L refactors
- [x] Branch off the working branch and write issues for the refactors.
- [ ] Test with older and newer iOS devices and simulators

**Comment by kcw-grunt** [comment]
Think you are ready to submit? It can be in stages @JasperHeist

**Comment by JCHeist** [comment]
Please see my question in #57
