### ISSUE TITLE
🥳[Feature] Re-add Donation using SafariViewController 

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-ios#61]
## Overview
The donation UI caused an App Store rejection in Nov 2020. The solution was a fix that caused users to simply not donate in the iOS version because the donation page is hidden.

### Why?
The  small donations sent from users are the engine to improve Litewallet. We spend hundreds (USD) each month for tools and services the donations help quite a bit.

## History
1. This button was in  the Send ViewController in the past.  And this work should put it back in the same place,

|Legacy Donation Button Location|
|------------------------|
|<img width="375" alt="Screen Shot 2020-10-11 at 1 31 43 PM" src="https://user-images.githubusercontent.com/2899463/125908083-8b320ae1-9f0a-4de5-b32b-d9b79e1865fc.png">|

2. Apple missed at first  it but eventually rejected the implementation and the wording since LF are not a charity
3. The only way to include it was that use a SafariViewController to drive users to a webpage (it can be a local .js or .html page)
4. Here is the commit last version prior: 45bd44dc
5. Here is the current path to have users donate: 
`Tap Hamburger > Tap Support the Litecoin Foundation > Copy address > _user must paste into send_`..🤨💩

## New UI/UX

The new flow should return the button to the SendViewController but there needs to have 3 steps:
1. User must tap on the Give button 
2. User must read and tap send in the disclaimer (This can be the SafariViewController)
3. UX navigates the user to the donation view

![New-Giving](https://user-images.githubusercontent.com/2899463/125907784-4c7bb225-4307-476d-a78f-5a29c5c5e039.png)

## Approach
- [ ] Review rejection language from Apple
- [ ]  Add code re-add the button in Send

**Comment by kcw-grunt** [comment]
cc: @JasperHeist

**Comment by kcw-grunt** [comment]
Hey @JasperHeist ,. will you pick this up? We can break it into tasks and start with an Epic branch if you like.

**Comment by JCHeist** [comment]
Can I review apple's rejection language somewhere? @kcw-grunt ?

**Comment by kcw-grunt** [comment]
Apple Rejection Explanation
<img width="365" alt="Screen Shot 2021-08-27 at 9 17 27 PM" src="https://user-images.githubusercontent.com/2899463/131184063-f3e37351-127a-4537-b607-81fa418b8e23.png">

**Comment by kcw-grunt** [comment]
@JasperHeist :☝🏾

**Comment by kcw-grunt** [comment]
will not do
