### ISSUE TITLE
🦺[Tech Debt] Add monitoring of API server in client for notification 

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-ios#69]
## Goal 
Make the team aware if the API server has an outage through the monitoring in the mobile app.  Offer a message in the Buy + tab for users rather than a 521 Error code

## Definition of Done
- [x] Add and test a monitoring function for when the mobile client first makes a query to the `litewallet-mobile-api` which fires a message/email to a mailing list
- [x] Add and test a monitoring function for when the mobile client first makes a query to  `any partner endpoint` which fires a message/email to a mailing list
- [x] Select the recipients in the mailing list
- [ ] Add a UI View explaining about the outage

**Comment by kcw-grunt** [comment]
cc: @gneo54

**Comment by JCHeist** [comment]
@kcw-grunt and @gneo54 What do you guys thing about integrating [Microsoft's AppCenter](https://docs.microsoft.com/en-us/appcenter/) into Litewallet. could plug in for the android app pretty easy as well. Looks like we could have a free analytics feature where we could send that this error happened and view in in thier dashboard.

**Comment by JCHeist** [comment]
@kcw-grunt thoughts on that service? Who should I collab with about this?

**Comment by kcw-grunt** [comment]
Thanks for the research on this @JasperHeist. We actually have this built into  our stack (Firebase) which is a competitor to AppCenter.
Since we are still fully utilizing the Firebase and Bitrise services, I wonder if we can find a solution without changing the stack.
Also, I have had some talks with a Data Scientist who wants to help us make sense of the Firebase and AppFigures analytics. 
Does this make sense?

**Comment by JCHeist** [comment]
Yeah that makes sense. Sounds like a better idea. I'll check if I have access to any of that and get in touch with you on slack.

**Comment by kcw-grunt** [comment]
85% done

**Comment by kcw-grunt** [comment]
# close

**Comment by kcw-grunt** [comment]
close
