### ISSUE TITLE
🥳[Feature] ENS Support

### ISSUE THREAD

**Issue by brantlymillegan** [litecoin-foundation/litewallet-ios#81]
### Why?
**Is your request related to a problem? Or, do you have an idea to improve the app? Please describe.**
Support for [ENS](https://ens.domains/) names for payments (ENS supports payments for all cryptos, including LTC; and in addition to .eth name also supports DNS names imported into ENS). You support Unstoppable Domains for some reason (a lower quality copy of ENS), and ENS has more features and is supported much much more widely.

### What?
**Describe the solution you'd like**
Add support for ENS

**Describe alternatives you've considered**

**Additional context**
https://docs.ens.domains/dapp-developer-guide/resolving-names

### Definition of Done
- I'm able to send LTC to any ENS name in the app

## UI Changes

|**Before**|**After**|
|----------|---------|
|||

**Comment by kcw-grunt** [comment]
Thanks @brantlymillegan for the input.
There are no plans to add alternatives to UD to Litewallet as our backlog is massive.  But, we will keep it mind for the future!

**Comment by brantlymillegan** [comment]
Oh yes I'm sure your backlog is big, just wondering why you'd add UD support in the first place then and not ENS when ENS is far bigger. Anyway, good luck w
