### ISSUE TITLE
🦺[Tech Debt] Update domain to litewallet.io

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-ios#89]
## Goal 
Update the domain from `lite-wallet.org` to `litewallet.io`

## Definition of Done
- [ ] Update resolves to litewallet.io
- [ ] `api-prod` and  `api-stage` subdomains remain the same

**Comment by remihoh** [comment]
Updated link to our new domain

techdebt/UpdateDomainToIO
